name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Start Supabase local
      run: supabase start

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest
      env:
        #---- HASH_SALT and SECRET_KEY must be 32bit long strings example below ----
        ALGORITHM: HS512
        DATABASE_URL: postgresql://postgres:postgres@localhost:15432/postgres
        HASH_SALT: p7K5wN3mX9r2bV6tQ1z8fG4jL0eC5vYd
        SECRET_KEY: 8xM2qB9vK1fL6tZ4wP3nG7jR0eC5sY2b
        